In [1]:
pip install duckdb

Requirement already satisfied: duckdb in c:\users\hrishi\anaconda3\lib\site-packages (1.5.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import duckdb

In [8]:
pip install --upgrade duckdb

Requirement already satisfied: duckdb in c:\users\hrishi\anaconda3\lib\site-packages (1.5.0)
Collecting duckdb
  Downloading duckdb-1.5.1-cp312-cp312-win_amd64.whl.metadata (4.2 kB)
Downloading duckdb-1.5.1-cp312-cp312-win_amd64.whl (13.1 MB)
   ---------------------------------------- 0.0/13.1 MB ? eta -:--:--
   --- ------------------------------------ 1.0/13.1 MB 6.3 MB/s eta 0:00:02
   --- ------------------------------------ 1.0/13.1 MB 6.3 MB/s eta 0:00:02
   --- ------------------------------------ 1.0/13.1 MB 6.3 MB/s eta 0:00:02
   --- ------------------------------------ 1.0/13.1 MB 6.3 MB/s eta 0:00:02
   ---- ----------------------------------- 1.6/13.1 MB 1.3 MB/s eta 0:00:10
   ------ --------------------------------- 2.1/13.1 MB 1.7 MB/s eta 0:00:07
   ------ --------------------------------- 2.1/13.1 MB 1.7 MB/s eta 0:00:07
   -------- ------------------------------- 2.6/13.1 MB 1.4 MB/s eta 0:00:08
   --------- ------------------------------ 3.1/13.1 MB 1.6 MB/s eta 0:00:07
   --------- ------------------------------ 3.1/13.1 MB 1.6 MB/s eta 0:00:07
   ---------- ----------------------------- 3.4/13.1 MB 1.4 MB/s eta 0:00:08
   ------------ --------------------------- 4.2/13.1 MB 1.6 MB/s eta 0:00:06
   -------------- ------------------------- 4.7/13.1 MB 1.6 MB/s eta 0:00:06
   ---------------- ----------------------- 5.2/13.1 MB 1.8 MB/s eta 0:00:05
   ------------------- -------------------- 6.3/13.1 MB 1.9 MB/s eta 0:00:04
   ------------------- -------------------- 6.3/13.1 MB 1.9 MB/s eta 0:00:04
   ------------------- -------------------- 6.3/13.1 MB 1.9 MB/s eta 0:00:04
   ------------------- -------------------- 6.3/13.1 MB 1.9 MB/s eta 0:00:04
   ------------------- -------------------- 6.3/13.1 MB 1.9 MB/s eta 0:00:04
   --------------------- ------------------ 7.1/13.1 MB 1.6 MB/s eta 0:00:04
   ---------------------- ----------------- 7.3/13.1 MB 1.6 MB/s eta 0:00:04
   ------------------------ --------------- 8.1/13.1 MB 1.7 MB/s eta 0:00:03
   ------------------------- -------------- 8.4/13.1 MB 1.7 MB/s eta 0:00:03
   ---------------------------- ----------- 9.4/13.1 MB 1.8 MB/s eta 0:00:03
   ---------------------------- ----------- 9.4/13.1 MB 1.8 MB/s eta 0:00:03
   ---------------------------- ----------- 9.4/13.1 MB 1.8 MB/s eta 0:00:03
   ---------------------------- ----------- 9.4/13.1 MB 1.8 MB/s eta 0:00:03
   ---------------------------- ----------- 9.4/13.1 MB 1.8 MB/s eta 0:00:03
   ------------------------------- -------- 10.2/13.1 MB 1.6 MB/s eta 0:00:02
   -------------------------------- ------- 10.5/13.1 MB 1.6 MB/s eta 0:00:02
   ---------------------------------- ----- 11.3/13.1 MB 1.7 MB/s eta 0:00:02
   ----------------------------------- ---- 11.5/13.1 MB 1.7 MB/s eta 0:00:01
   ----------------------------------- ---- 11.5/13.1 MB 1.7 MB/s eta 0:00:01
   ----------------------------------- ---- 11.5/13.1 MB 1.7 MB/s eta 0:00:01
   ----------------------------------- ---- 11.5/13.1 MB 1.7 MB/s eta 0:00:01
   ------------------------------------- -- 12.3/13.1 MB 1.6 MB/s eta 0:00:01
   ---------------------------------------  12.8/13.1 MB 1.6 MB/s eta 0:00:01
   ---------------------------------------  12.8/13.1 MB 1.6 MB/s eta 0:00:01
   ---------------------------------------- 13.1/13.1 MB 1.6 MB/s eta 0:00:00
Installing collected packages: duckdb
  Attempting uninstall: duckdb
    Found existing installation: duckdb 1.5.0
    Uninstalling duckdb-1.5.0:
      Successfully uninstalled duckdb-1.5.0
Successfully installed duckdb-1.5.1
Note: you may need to restart the kernel to use updated packages.

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Hrishi\AppData\Local\Temp\pip-uninstall-ya3z1qpe'.
  You can safely remove it manually.

In [9]:
df = duckdb.query("""
    SELECT * FROM read_csv_auto('customers.csv')
""").df()

df

   customer_id           name       city signup_date               email
0      CUST001     Rohan Iyer    Kolkata  2023-04-16   user1@example.com
1      CUST002    Aditya Shah     Mumbai  2022-06-11   user2@example.com
2      CUST003    Arjun Singh       Pune  2023-03-15   user3@example.com
3      CUST004     Neha Joshi     Mumbai  2022-11-06   user4@example.com
4      CUST005    Divya Joshi     Mumbai  2023-11-02   user5@example.com
5      CUST006    Neha Sharma    Chennai  2023-01-16   user6@example.com
6      CUST007      Pooja Rao    Chennai  2023-10-03   user7@example.com
7      CUST008      Amit Iyer     Mumbai  2023-11-03   user8@example.com
8      CUST009     Riya Verma      Delhi  2022-08-07   user9@example.com
9      CUST010    Kavya Menon       Pune  2023-08-31  user10@example.com
10     CUST011    Rohan Mehta       Pune  2023-04-01  user11@example.com
11     CUST012    Sneha Patel       Pune  2022-12-18  user12@example.com
12     CUST013     Riya Verma      Delhi  2022-05-16  user13@example.com
13     CUST014      Amit Iyer     Mumbai  2023-01-28  user14@example.com
14     CUST015    Divya Desai      Delhi  2022-11-17  user15@example.com
15     CUST016   Vikram Singh     Mumbai  2023-01-27  user16@example.com
16     CUST017   Nikhil Mehta  Hyderabad  2023-06-28  user17@example.com
17     CUST018      Neha Shah  Bangalore  2023-10-28  user18@example.com
18     CUST019   Vikram Patel  Hyderabad  2022-08-07  user19@example.com
19     CUST020    Arjun Verma     Mumbai  2023-03-30  user20@example.com
20     CUST021   Sneha Chopra       Pune  2022-05-24  user21@example.com
21     CUST022    Divya Patel  Bangalore  2023-01-29  user22@example.com
22     CUST023    Kavya Joshi       Pune  2022-05-24  user23@example.com
23     CUST024   Kavya Tiwari  Hyderabad  2022-03-28  user24@example.com
24     CUST025    Aarav Desai    Kolkata  2023-09-07  user25@example.com
25     CUST026     Pooja Nair  Hyderabad  2022-01-28  user26@example.com
26     CUST027    Suresh Nair       Pune  2023-09-14  user27@example.com
27     CUST028   Pooja Sharma    Kolkata  2023-02-06  user28@example.com
28     CUST029     Riya Reddy     Mumbai  2022-09-03  user29@example.com
29     CUST030       Riya Das     Mumbai  2022-09-04  user30@example.com
30     CUST031   Rohan Pillai  Bangalore  2023-06-25  user31@example.com
31     CUST032   Kiran Chopra    Chennai  2022-05-16  user32@example.com
32     CUST033  Lakshmi Gupta    Kolkata  2023-01-10  user33@example.com
33     CUST034     Amit Mehta  Hyderabad  2023-04-28  user34@example.com
34     CUST035    Rohan Joshi      Delhi  2022-03-11  user35@example.com
35     CUST036    Priya Reddy  Hyderabad  2022-02-10  user36@example.com
36     CUST037   Suresh Patel    Chennai  2022-10-21  user37@example.com
37     CUST038    Amit Tiwari  Hyderabad  2023-02-16  user38@example.com
38     CUST039   Vikram Joshi     Mumbai  2023-09-23  user39@example.com
39     CUST040     Amit Menon      Delhi  2022-11-14  user40@example.com
40     CUST041  Lakshmi Kumar    Chennai  2022-06-09  user41@example.com
41     CUST042     Amit Desai       Pune  2023-08-24  user42@example.com
42     CUST043   Kavya Sharma      Delhi  2023-03-24  user43@example.com
43     CUST044     Meera Iyer    Chennai  2022-03-30  user44@example.com
44     CUST045   Aarav Sharma  Bangalore  2023-09-19  user45@example.com
45     CUST046      Neha Iyer     Mumbai  2023-11-14  user46@example.com
46     CUST047    Rohan Gupta    Chennai  2022-05-21  user47@example.com
47     CUST048   Suresh Menon    Kolkata  2022-12-22  user48@example.com
48     CUST049    Neha Pillai      Delhi  2022-09-23  user49@example.com
49     CUST050    Sneha Mehta  Bangalore  2022-10-03  user50@example.com

In [11]:
import duckdb

df = duckdb.query("""
    SELECT * FROM read_parquet('products.parquet')
""").df()

df

,line_item_id,order_id,product_id,product_name,category,quantity,unit_price,total_price
0,LI0001,ORD2007,PR02,Cotton Kurti,Clothing,4,899,3596
1,LI0002,ORD2057,PR07,Yoga Mat,Sports,1,699,699
2,LI0003,ORD2071,PR05,Python Book,Books,4,799,3196
3,LI0004,ORD2090,PR03,Basmati Rice 5kg,Grocery,2,450,900
4,LI0005,ORD2089,PR01,Wireless Earbuds,Electronics,3,2499,7497
...,...,...,...,...,...,...,...,...
95,LI0096,ORD2018,PR07,Yoga Mat,Sports,5,699,3495
96,LI0097,ORD2090,PR09,Mechanical Keyboard,Electronics,3,4599,13797
97,LI0098,ORD2090,PR09,Mechanical Keyboard,Electronics,3,4599,13797
98,LI0099,ORD2092,PR09,Mechanical Keyboard,Electronics,2,4599,9198
99,LI0100,ORD2026,PR04,Running Shoes,Footwear,5,3299,16495

In [17]:
df = duckdb.query("""
    SELECT * FROM read_json_auto('orders.json')
""").df()

df

   order_id customer_id order_date      status  total_amount  num_items
0   ORD2001     CUST028 2023-05-20   delivered          2397          1
1   ORD2002     CUST032 2023-08-22   delivered          6197          3
2   ORD2003     CUST037 2023-12-12   delivered          9897          1
3   ORD2004     CUST003 2023-01-07     shipped          5596          2
4   ORD2005     CUST012 2023-01-19  processing         15792          4
..      ...         ...        ...         ...           ...        ...
95  ORD2096     CUST011 2023-02-03   cancelled          1598          1
96  ORD2097     CUST047 2023-09-24     shipped          3497          3
97  ORD2098     CUST026 2023-01-10   delivered          4649          2
98  ORD2099     CUST038 2023-09-16   delivered          6294          2
99  ORD2100     CUST025 2023-11-24   delivered         21093          3

[100 rows x 6 columns]

In [ ]:
#List all customers along with the total number of orders they have placed

In [22]:
duckdb.sql("""
SELECT 
    c.customer_id,
    c.name,
    COUNT(o.order_id) AS total_orders
FROM read_csv_auto('customers.csv') c
LEFT JOIN read_json_auto('orders.json') o
ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.name""").show()

┌─────────────┬───────────────┬──────────────┐
│ customer_id │     name      │ total_orders │
│   varchar   │    varchar    │    int64     │
├─────────────┼───────────────┼──────────────┤
│ CUST004     │ Neha Joshi    │            6 │
│ CUST005     │ Divya Joshi   │            3 │
│ CUST006     │ Neha Sharma   │            4 │
│ CUST020     │ Arjun Verma   │            3 │
│ CUST021     │ Sneha Chopra  │            1 │
│ CUST027     │ Suresh Nair   │            1 │
│ CUST037     │ Suresh Patel  │            3 │
│ CUST039     │ Vikram Joshi  │            1 │
│ CUST045     │ Aarav Sharma  │            1 │
│ CUST047     │ Rohan Gupta   │            3 │
│    ·        │      ·        │            · │
│    ·        │      ·        │            · │
│    ·        │      ·        │            · │
│ CUST011     │ Rohan Mehta   │            5 │
│ CUST014     │ Amit Iyer     │            1 │
│ CUST016     │ Vikram Singh  │            4 │
│ CUST019     │ Vikram Patel  │            2 │
│ CUST035     │ Rohan Joshi   │            1 │
│ CUST041     │ Lakshmi Kumar │            3 │
│ CUST001     │ Rohan Iyer    │            0 │
│ CUST024     │ Kavya Tiwari  │            0 │
│ CUST033     │ Lakshmi Gupta │            0 │
│ CUST049     │ Neha Pillai   │            0 │
└─────────────┴───────────────┴──────────────┘
  50 rows (20 shown)               3 columns

In [ ]:
#Find the top 3 customers by total order value

In [31]:
duckdb.sql("""
SELECT 
    c.customer_id,
    c.name,
    SUM(o.total_amount) AS total_order_value
FROM read_csv_auto('customers.csv') c
JOIN read_json_auto('orders.json') o
ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.name
ORDER BY total_order_value DESC
LIMIT 3
""").show()

┌─────────────┬──────────────┬───────────────────┐
│ customer_id │     name     │ total_order_value │
│   varchar   │   varchar    │      int128       │
├─────────────┼──────────────┼───────────────────┤
│ CUST025     │ Aarav Desai  │             50331 │
│ CUST004     │ Neha Joshi   │             45527 │
│ CUST048     │ Suresh Menon │             40629 │
└─────────────┴──────────────┴───────────────────┘

In [ ]:
#List all products purchased by customers from Bangalore

In [32]:
duckdb.sql("""
SELECT DISTINCT 
    p.product_name
FROM read_csv_auto('customers.csv') c
JOIN read_json_auto('orders.json') o
ON c.customer_id = o.customer_id
JOIN read_parquet('products.parquet') p
ON o.order_id = p.order_id
WHERE c.city = 'Bangalore'
""").show()

┌──────────────────┐
│   product_name   │
│     varchar      │
├──────────────────┤
│ Denim Jeans      │
│ Python Book      │
│ Desk Lamp        │
│ Wireless Earbuds │
│ Cotton Kurti     │
└──────────────────┘

In [ ]:
#Join all three files to show: customer name, order date, product name, and quantity

In [33]:
duckdb.sql("""
SELECT 
    c.name AS customer_name,
    o.order_date,
    p.product_name,
    p.quantity
FROM read_csv_auto('customers.csv') c
JOIN read_json_auto('orders.json') o
ON c.customer_id = o.customer_id
JOIN read_parquet('products.parquet') p
ON o.order_id = p.order_id
""").show()

┌───────────────┬────────────┬─────────────────────┬──────────┐
│ customer_name │ order_date │    product_name     │ quantity │
│    varchar    │    date    │       varchar       │  int64   │
├───────────────┼────────────┼─────────────────────┼──────────┤
│ Aditya Shah   │ 2023-09-27 │ Face Wash           │        2 │
│ Arjun Singh   │ 2023-03-30 │ Basmati Rice 5kg    │        5 │
│ Neha Joshi    │ 2023-09-01 │ Desk Lamp           │        1 │
│ Divya Joshi   │ 2023-10-31 │ Cotton Kurti        │        2 │
│ Neha Sharma   │ 2023-06-19 │ Running Shoes       │        5 │
│ Pooja Rao     │ 2023-08-25 │ Basmati Rice 5kg    │        1 │
│ Amit Iyer     │ 2023-09-15 │ Basmati Rice 5kg    │        4 │
│ Riya Verma    │ 2023-09-26 │ Yoga Mat            │        4 │
│ Rohan Mehta   │ 2023-02-03 │ Wireless Earbuds    │        1 │
│ Sneha Patel   │ 2023-05-21 │ Face Wash           │        2 │
│     ·         │     ·      │     ·               │        · │
│     ·         │     ·      │     ·               │        · │
│     ·         │     ·      │     ·               │        · │
│ Amit Iyer     │ 2023-08-01 │ Running Shoes       │        4 │
│ Sneha Patel   │ 2023-08-17 │ Yoga Mat            │        1 │
│ Vikram Singh  │ 2023-05-30 │ Python Book         │        1 │
│ Kiran Chopra  │ 2023-12-05 │ Running Shoes       │        4 │
│ Suresh Menon  │ 2023-02-13 │ Mechanical Keyboard │        5 │
│ Neha Joshi    │ 2023-09-01 │ Denim Jeans         │        1 │
│ Kiran Chopra  │ 2023-08-22 │ Cotton Kurti        │        1 │
│ Neha Joshi    │ 2023-04-24 │ Denim Jeans         │        4 │
│ Neha Joshi    │ 2023-11-04 │ Running Shoes       │        4 │
│ Neha Joshi    │ 2023-09-01 │ Running Shoes       │        3 │
└───────────────┴────────────┴─────────────────────┴──────────┘
  100 rows (20 shown)                               4 columns